export const USER_REPOSITORY = 'USER_REPOSITORY';

export const PASSWORD_HASHER = 'PASSWORD_HASHER';

export const TOKEN_PROVIDER = 'TOKEN_PROVIDER';

export const EMAIL_PROVIDER = 'EMAIL_PROVIDER';

export const CACHE_PROVIDER = 'CACHE_PROVIDER';
